parameters:
  patreon_client_id: V8Glais1m7K5z9nNZQOH6uSjOeuCJrEMC0tAo1HMB7JfsIHyqia1GKQ-TpNlwTrI
  patreon_client_secret: sK9MitFaIE_YyInNZszI50QX0argW4XGRaBDZqq_UiTOBu41QEaDtO8_O07Elc7t
  patreon_creator_id: hazardcreative
